apiVersion: apps/v1
kind: Deployment
metadata:
  name: testing-lcl-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: testing-lcl
  template:
    metadata:
      labels:
        app: testing-lcl
    spec:
      containers:
        - name: simple-api-container
          image: asia-southeast2-docker.pkg.dev/lcl-tesing/simple-api-repo/simple-api:v1
          ports:
            - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: testing-lcl-service
spec:
  type: LoadBalancer
  selector:
    app: testing-lcl
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  